# Generated by Django 4.0.3 on 2022-03-19 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artle_platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='template',
            name='url',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='music_question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artle_platform.musicquestion'),
            preserve_default=False,
        ),
    ]
