# Generated by Django 4.0.3 on 2022-03-19 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artle_platform', '0002_musicquestion_alter_template_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='artle_platform.musicquestion'),
        ),
        migrations.AlterField(
            model_name='template',
            name='url',
            field=models.TextField(blank=True, default=None),
        ),
    ]
