# Generated by Django 4.0.3 on 2022-03-19 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artle_platform', '0003_alter_music_music_question_alter_template_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawingWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RhymeWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='template',
            name='can_like',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='template',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='template',
            name='user_thought',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.CreateModel(
            name='Rhyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rhyme_word', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='artle_platform.rhymeword')),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='artle_platform.template')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_question', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='artle_platform.quotequestion')),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='artle_platform.template')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='artle_platform.template')),
            ],
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing_word', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='artle_platform.drawingword')),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='artle_platform.template')),
            ],
        ),
    ]
